# hash:sha256:833eece9c95cf509a6958281a038a0ffb139446536af2e12f8e13f23482f56ed
FROM registry.acmecorp-edge.codeocean.com/codeocean/bioinformatics:2.0.0

ARG DEBIAN_FRONTEND=noninteractive

ARG GIT_ASKPASS
ARG GIT_ACCESS_TOKEN
COPY git-askpass /

ENV Camels=100
